#!/bin/bash
LIB="/usr/share/java"
java -Djava.library.path="/usr/lib/jni" -classpath $LIB/libfirmapiu-java.jar:$LIB/firmapiu-daemon.jar:$LIB/bcprov.jar:$LIB/bcpkix.jar:$LIB/unix.jar:$LIB/hexdump.jar:$LIB/dbus.jar it.libersoft.firmapiud.FirmapiuD $1
